"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import { AppWrapper } from "../../styled";
import Header from "./components/Header/Header";
import { getServerSession } from "next-auth";
import LoginPage from "./pages/login/page";
import { signOut } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children?: React.ReactNode;
};

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line @next/next/no-async-client-component
export default async function RootLayout({ children }: Props) {
  const session = await getServerSession();
  const isLoggedIn = session?.user;
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <AppWrapper>
            {isLoggedIn ? (
              <>
                <Header />
                <button onClick={() => signOut()}>logout</button>
                {children}
              </>
            ) : (
              <LoginPage />
            )}
          </AppWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
