"use client";
import { UserProvider } from "@/app/hooks/userContext";
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children?: React.ReactNode;
  params?: any;
};

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({ children, params: { session } }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <UserProvider>
            <QueryClientProvider client={queryClient}>
              <LayoutWithHeader>{children}</LayoutWithHeader>{" "}
            </QueryClientProvider>
          </UserProvider>
        </SessionProvider>
      </body>
    </html>
  );
}

export function LayoutWithHeader({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
